- name: restart operating system
  become: yes
  command: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  notify: wait for operating system to restart

# - name: wait for operating system to restart
#   delegate_to: localhost
#   wait_for:
#     host: "{{inventory_hostname}}"
#     port: 22
#     state: started
#     delay: 60
#     timeout: 300
#     retries: 2
#     delay: 10

- name: wait for operating system to restart
  local_action: wait_for host={{ ansible_ssh_host }} state=started
  become: false
