---

- name: Install Debian Packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
  - git
  - vim
  - htop
  - unzip
  - xauth
  - mc
  when: ansible_os_family == "Debian"

- name: Downloading and enable the EPEL repository definitions.
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: enable the EPEL repository definitions - CentOS 7
  yum: name=epel-release
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Install Redhat Packages
  yum: name="{{ item }}" state=present
  with_items:
  - java
  - git
  - vim
  - htop
  - mc
  - unzip
  - xauth
  when: ansible_os_family == "RedHat"

- name: Disable iptables
  action: service name=iptables state=stopped enabled=false
  when: ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Disable firewalld
  action: service name=firewalld state=stopped enabled=false
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  ignore_errors: yes

- name: Remove require tty
  lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent

- name: Remove require tty - alt
  lineinfile: regexp="requiretty" dest=/etc/sudoers.d/os_defaults state=absent
