- name: Create security groups
  environment: "{{openstack_environment}}"
  os_security_group:
    name: "{{item.name}}"
    description: "{{item.description}}"
    availability_zone: AZ2
    state: present
  with_items: "{{security_groups}}"

- name: Add security group rules
  environment: "{{openstack_environment}}"
  os_security_group_rule:
    security_group: "{{item.0.name}}"
    protocol: "{{item.1.protocol}}"
    ethertype: IPv4
    port_range_min: "{{item.1.port_range_min}}"
    port_range_max: "{{item.1.port_range_max}}"
    remote_ip_prefix: 0.0.0.0/0
    direction: ingress
    availability_zone: AZ2
    state: present
  with_subelements:
    - "{{security_groups}}"
    - ports
