---
- hosts: all
  environment: "{{http_proxy_environment}}"
  gather_facts: yes
  become: yes
  roles:
    - common
    - role: peru.proxy_settings
      proxy_settings_http_proxy: 'http://web-proxy.corp.hpecorp.net:8080'
      proxy_settings_ftp_proxy: 'http://web-proxy.corp.hpecorp.net:8080'
      proxy_settings_https_proxy: 'http://web-proxy.corp.hpecorp.net:8080'
      proxy_settings_no_proxy: 'localhost,.hpe.com,.hpecorp.net,127.0.0.1,10.0.0.0/16,172.16.1.0/24,192.168.0.0/16'
      proxy_settings_yum_proxy: 'http://web-proxy.corp.hpecorp.net:8080'
      proxy_settings_yum_proxy_username: ''
      proxy_settings_yum_proxy_password: ''
